version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: LiveStock/Dockerfile
    container_name: livestock-backend
    ports:
      - "8080:8080" # host:container
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./InventoryApp-frontend
      dockerfile: Dockerfile
    container_name: livestock-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
